// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfo2-9K7dE2kCtMU02griE08cmDL5oAHU',
    appId: '1:148826667642:android:ffb60cb484e1f52e2a99c3',
    messagingSenderId: '148826667642',
    projectId: 'cs4750-app',
    storageBucket: 'cs4750-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG191FHipUnO2ETQR6CfY90P6xkVPiC3s',
    appId: '1:148826667642:ios:55ea208874c08fc02a99c3',
    messagingSenderId: '148826667642',
    projectId: 'cs4750-app',
    storageBucket: 'cs4750-app.appspot.com',
    iosClientId: '148826667642-6q68dfnbol24fof0ovc0eegf59qckfka.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppProjectGarden',
  );
}
